name: Github Pages Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v4
        id: node-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Deploy with Lerna
        run: npx lerna run deploy
